version: '3'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: cyclone129

    prisma:
        image: prismagraphql/prisma:1.31
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        port: 5432
                        user: root
                        password: cyclone129
                        migrations: true
