version: '3'
services:
    postgres:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: cyclone129

    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                    default:
                        connector: mysql
                        host: mysql
                        port: 3306
                        user: root
                        password: cyclone129
                        migrations: true
